/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *  By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * */
package project_eular;

public class Question2 {
private static final int max_value=4000000;
	public static void main(String[] args) {
		int num1=1;
		int num2=2;
		int sum=getNextFibonacci(num1,num2);
		System.out.print(sum);

	}
	private static int getNextFibonacci(int num1, int num2) {
		if(num1>max_value||num2>max_value)
		return 0;
		int sum=0;
		if(num2%2==0) {
			sum+=num2;
			//checking num2 only as num1 of this method was num 2 for previous recursion
		}
		int next_num=num1+num2;
		return sum+getNextFibonacci(num2, next_num);
	}

}
/*
 * Output
 * 4613732
 * */
